# Generated by Django 3.2.4 on 2021-06-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='image',
            name='custom_image',
            field=models.ImageField(blank=True, upload_to='custom_img/%Y-%m-%d-%s'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='origin_img/%Y-%m-%d-%s', verbose_name='Файл'),
        ),
    ]
